name: Create Weblate PR
on:
  push:
    branches:
      - feat-weblate-cidgravity-*
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Get target branch
        id: get-target-branch
        uses: actions/github-script@v6
        with:
          script: |
            const targetBranch = context.ref.split('-')[3]
            core.setOutput('targetBranch', targetBranch)
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}
      - name: Create Pull Request
        run: |
          sudo apt-get install expect
          cd $GITHUB_WORKSPACE
          PR_CREATION_RESULT=$(unbuffer gh pr create -d -B ${{steps.get-target-branch.outputs.targetBranch}} -H ${{github.ref_name}} --title 'Update Translations from Weblate' --body 'Update translations from Weblate. PR automatically created by CI on branch push.')
          if [[ $PR_CREATION_RESULT == *"already exists"* ]]; then
            exit 0;
          fi
          if [[ $PR_CREATION_RESULT == "" ]]; then
            exit 0;
          fi
          echo $PR_CREATION_RESULT
          exit 1;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
