name: Create Weblate PR
on:
  push:
    branches:
      - feat-weblate-cidgravity-*
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Get target branch
        id: get-target-branch
        uses: actions/github-script@v6
        with:
          script: |
            const targetBranch = context.ref.split('-')[3]
            console.log(targetBranch, context.ref)
            core.setOutput('targetBranch', targetBranch)
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{steps.get-target-branch.outputs.targetBranch}}
          title: Update Translations from Weblate - ${{steps.get-target-branch.outputs.targetBranch}}
          body: Update translations from Weblate. PR automatically created by CI on branch push.
          branch: ${{github.ref_name}}
          draft: true
